version: 2

models:
  - name: stg_ga__events
    description: GAのイベントを `event_date` でパーティショニングしたテーブル

  # 基本イベントテーブル
  - name: stg_ga__page_views
    description: ページビューイベント
    columns:
      - name: page_url
        tests:
          - not_null
  - name: stg_ga__clicks
    description: クリックイベント
    columns:
      - name: link_url
        tests:
          - not_null
  - name: stg_ga__read_to_ends
    description: 読了時に記録されるイベント
    columns:
      - name: article_id
        tests:
          - not_null
  
  # 集計済みテーブル
  - name: stg_ga__sessions
    description: セッション情報
  #   columns:
  #     - name: session_key
  #       tests:
          # - not_null
          # - unique
  - name: stg_ga__users
    description: ユーザー情報