version: 2

sources:
  - name: ga
    database: "{{ env_var('DBT_GCP_PROJECT') }}"
    schema: "{{ env_var('DBT_DATASET') }}"
    tables:
      - name: events
        identifier: events_*
        description: GA4連携でBigQueryへ保存された、日付別にシャーディングされたテーブル
