{%- macro classify_region(country, region) -%}

    case
        when {{ country }} <> 'Japan' then {{ country }}
        when {{ region }} = 'Hokkaido' then '北海道'
        when {{ region }} = 'Aomori' then '青森県'
        when {{ region }} = 'Iwate' then '岩手県'
        when {{ region }} = 'Miyagi' then '宮城県'
        when {{ region }} = 'Akita' then '秋田県'
        when {{ region }} = 'Yamagata' then '山形県'
        when {{ region }} = 'Fukushima' then '福島県'
        when {{ region }} = 'Ibaraki' then '茨城県'
        when {{ region }} = 'Tochigi' then '栃木県'
        when {{ region }} = 'Gunma' then '群馬県'
        when {{ region }} = 'Saitama' then '埼玉県'
        when {{ region }} = 'Chiba' then '千葉県'
        when {{ region }} = 'Tokyo' then '東京都'
        when {{ region }} = 'Kanagawa' then '神奈川県'
        when {{ region }} = 'Niigata' then '新潟県'
        when {{ region }} = 'Toyama' then '富山県'
        when {{ region }} = 'Ishikawa' then '石川県'
        when {{ region }} = 'Fukui' then '福井県'
        when {{ region }} = 'Yamanashi' then '山梨県'
        when {{ region }} = 'Nagano' then '長野県'
        when {{ region }} = 'Gifu' then '岐阜県'
        when {{ region }} = 'Shizuoka' then '静岡県'
        when {{ region }} = 'Aichi' then '愛知県'
        when {{ region }} = 'Mie' then '三重県'
        when {{ region }} = 'Shiga' then '滋賀県'
        when {{ region }} = 'Kyoto' then '京都府'
        when {{ region }} = 'Osaka' then '大阪府'
        when {{ region }} = 'Hyogo' then '兵庫県'
        when {{ region }} = 'Nara' then '奈良県'
        when {{ region }} = 'Wakayama' then '和歌山県'
        when {{ region }} = 'Tottori' then '鳥取県'
        when {{ region }} = 'Shimane' then '島根県'
        when {{ region }} = 'Okayama' then '岡山県'
        when {{ region }} = 'Hiroshima' then '広島県'
        when {{ region }} = 'Yamaguchi' then '山口県'
        when {{ region }} = 'Tokushima' then '徳島県'
        when {{ region }} = 'Kagawa' then '香川県'
        when {{ region }} = 'Ehime' then '愛媛県'
        when {{ region }} = 'Kochi' then '高知県'
        when {{ region }} = 'Fukuoka' then '福岡県'
        when {{ region }} = 'Saga' then '佐賀県'
        when {{ region }} = 'Nagasaki' then '長崎県'
        when {{ region }} = 'Kumamoto' then '熊本県'
        when {{ region }} = 'Oita' then '大分県'
        when {{ region }} = 'Miyazaki' then '宮崎県'
        when {{ region }} = 'Kagoshima' then '鹿児島県'
        when {{ region }} = 'Okinawa' then '沖縄県'
        else 'その他'
    end

{%- endmacro -%}